# Prefix PR Labeler Configuration
# Maps PR title prefixes to labels

prefixes:
  - prefix: "feat"
    label: "feature"
  - prefix: "feature"
    label: "feature"
  - prefix: "fix"
    label: "fix"
  - prefix: "bugfix"
    label: "fix"
  - prefix: "docs"
    label: "documentation"
  - prefix: "doc"
    label: "documentation"
  - prefix: "style"
    label: "cleanup"
  - prefix: "format"
    label: "cleanup"
  - prefix: "refactor"
    label: "refactor"
  - prefix: "perf"
    label: "performance"
  - prefix: "performance"
    label: "performance"
  - prefix: "test"
    label: "test"
  - prefix: "tests"
    label: "test"
  - prefix: "chore"
    label: "chore"
  - prefix: "build"
    label: "chore"
  - prefix: "ci"
    label: "chore"
  - prefix: "deps"
    label: "dependencies"
  - prefix: "dependencies"
    label: "dependencies"
  - prefix: "example"
    label: "example"
  - prefix: "demo"
    label: "example"
  - prefix: "security"
    label: "security"
  - prefix: "breaking"
    label: "breaking-change"
  - prefix: "breaking-change"
    label: "breaking-change"
