blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/MatiPl01/react-native-sortables/discussions/categories/q&a
    about: You can ask and answer questions here.
  - name: Feature request
    url: https://github.com/MatiPl01/react-native-sortables/discussions/categories/ideas
    about: You can submit feature requests here.
