# PR Labeler Configuration
# Handles both title prefixes AND file changes in a single action

# Title-based labeling
titleMappings:
  - label: feature
    prefixes:
      - feat
      - feature

  - label: fix
    prefixes:
      - fix
      - bugfix

  - label: documentation
    prefixes:
      - docs
      - doc

  - label: cleanup
    prefixes:
      - style
      - format

  - label: refactor
    prefixes:
      - refactor

  - label: performance
    prefixes:
      - perf
      - performance

  - label: test
    prefixes:
      - test
      - tests

  - label: chore
    prefixes:
      - chore
      - build

  - label: ci
    prefixes:
      - ci

  - label: dependencies
    prefixes:
      - deps
      - dependencies

  - label: example
    prefixes:
      - example
      - demo

  - label: enhancement
    prefixes:
      - enhancement

  - label: critical
    prefixes:
      - critical

  - label: released
    prefixes:
      - released

# File-based labeling
fileMappings:
  - label: documentation
    patterns:
      - "packages/docs/**"
      - "**/README.md"
      - "**/*.md"

  - label: example
    patterns:
      - "example/**"

  - label: test
    patterns:
      - "**/*.test.*"
      - "**/*.spec.*"
      - "**/__tests__/**"
      - "**/tests/**"
      - "**/__mocks__/**"

  - label: ci
    patterns:
      - ".github/**"
      - "**/workflows/**"
      - "**/.github/**"

  - label: dependencies
    patterns:
      - "**/package.json"
      - "**/yarn.lock"
      - "**/package-lock.json"
      - "**/pnpm-lock.yaml"
      - "**/bun.lockb"
