name: '🏷️ Unified PR Labeler'

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Label PR based on title and files
        uses: ./.github/actions/labeler
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          # Optional: Use custom config file (default: labeler-config.yml)
          # config-file: 'custom-labeler-config.yml'
